name: build

on:
  workflow_call:
    inputs:
      context:
        description: context of docker/build-push-action
        type: string
        required: false
      build-args:
        description: build-args of docker/build-push-action
        type: string
        required: false
      image:
        description: images of docker/metadata-action
        type: string
        required: false
        default: ghcr.io/${{ github.repository }}
      platforms:
        description: platforms of docker/build-push-action
        type: string
        required: false
      flavor:
        description: flavor of docker/metadata-action
        type: string
        required: false
    outputs:
      digest:
        description: image digest (e.g. sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef)
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: metadata
        with:
          images: ${{ inputs.image }}
          flavor: ${{ inputs.flavor }}
      - uses: int128/docker-build-cache-config-action@0b4582921757b6145fd7fab8156c725b28e1c2b8 # v1.31.0
        id: cache
        with:
          image: ${{ inputs.image }}/cache
          flavor: ${{ inputs.flavor }}
      - uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      - uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - uses: docker/build-push-action@4f7cdeb0f05278b464e71357394bf2c61f94138e # v6.6.0
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ inputs.platforms }}
