name: build

on:
  workflow_call:
    inputs:
      context:
        description: context of docker/build-push-action
        type: string
        required: false
      build-args:
        description: build-args of docker/build-push-action
        type: string
        required: false
      image:
        description: images of docker/metadata-action
        type: string
        required: false
        default: ghcr.io/${{ github.repository }}
      platforms:
        description: platforms of docker/build-push-action
        type: string
        required: false
      flavor:
        description: flavor of docker/metadata-action
        type: string
        required: false
    outputs:
      digest:
        description: image digest (e.g. sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef)
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: metadata
        with:
          images: ${{ inputs.image }}
          flavor: ${{ inputs.flavor }}
      - uses: int128/docker-build-cache-config-action@0b4582921757b6145fd7fab8156c725b28e1c2b8 # v1.31.0
        id: cache
        with:
          image: ${{ inputs.image }}/cache
          flavor: ${{ inputs.flavor }}
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0
      - uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          context: ${{ inputs.context }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ inputs.platforms }}
