name: build

on:
  workflow_call:
    inputs:
      context:
        description: build context
        type: string
        required: false
      platforms:
        description: target platform
        type: string
        required: false
      suffix:
        description: suffix of the image tag
        type: string
        required: false
    outputs:
      digest: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: suffix=${{ input.suffix }}
      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ghcr.io/${{ github.repository }}/cache
          tag-suffix: ${{ input.suffix }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          context: ${{ input.context }}
          platforms: ${{ input.platform }}
