name: build-multi-architecture

on:
  workflow_call:
    inputs:
      context:
        description: context of docker/build-push-action
        type: string
        required: false
      build-args:
        description: build-args of docker/build-push-action
        type: string
        required: false
      platforms:
        description: Platforms (JSON string)
        type: string
        default: |
          ["linux/amd64", "linux/arm64"]

jobs:
  for:
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(inputs.platforms) }}
    uses: ./.github/workflows/build.yaml
    with:
      context: ${{ inputs.context }}
      build-args: ${{ inputs.build-args }}
      platforms: ${{ matrix.platform }}
      # avoid overwriting the latest tag because metadata-action does not add a suffix to it
      flavor: latest=false,suffix=-${{ matrix.platform }}

  multi-architecture:
    needs:
      - for
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: actions/github-script@v7
        id: suffixes
        env:
          platforms: ${{ inputs.platforms }}
        with:
          result-encoding: string
          script: |
            const platforms = JSON.parse(process.env.platforms)
            return platforms.map((platform) => `-${platform.replaceAll(/\//g, '-')}`).join(`\n`)
      - uses: int128/docker-manifest-create-action@v1
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          suffixes: ${{ steps.suffixes.outputs.result }}
