name: build

on:
  workflow_call:
    inputs:
      context:
        description: context of docker/build-push-action
        type: string
        required: false
      build-args:
        description: build-args of docker/build-push-action
        type: string
        required: false
      image:
        description: images of docker/metadata-action
        type: string
        required: false
        default: ghcr.io/${{ github.repository }}
      platforms:
        description: platforms of docker/build-push-action
        type: string
        required: false
      flavor:
        description: flavor of docker/metadata-action
        type: string
        required: false
      mount-actions-cache:
        description: If set, mount actions/cache into the builder container
        type: boolean
        required: false
    outputs:
      digest:
        description: image digest (e.g. sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef)
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@31cebacef4805868f9ce9a0cb03ee36c32df2ac4 # v5.3.0
        id: metadata
        with:
          images: ${{ inputs.image }}
          flavor: ${{ inputs.flavor }}
      - uses: int128/docker-build-cache-config-action@1ae274f683e01b2b3eb290167f51590fd7035316 # v1.28.0
        id: cache
        with:
          image: ${{ inputs.image }}/cache
          flavor: ${{ inputs.flavor }}

      - if: inputs.mount-actions-cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/actions-cache-docker-build
          key: ${{ inputs.image }}-${{ github.sha }}
          restore-keys: ${{ inputs.image }}-
      - if: inputs.mount-actions-cache
        id: actions-cache-docker-build-context
        run: echo "value=actions_cache=$HOME/actions-cache-docker-build" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          context: ${{ inputs.context }}
          build-contexts: ${{ steps.actions-cache-docker-build-context.outputs.value }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ inputs.platforms }}
