name: build

on:
  workflow_call:
    inputs:
      context:
        description: build context
        type: string
        required: false
      image:
        description: image name
        type: string
        required: false
        default: ghcr.io/${{ github.repository }}
      platforms:
        description: target platforms
        type: string
        required: false
      flavor:
        description: metadata flavor (see docker/metadata-action)
        type: string
        required: false
    outputs:
      digest:
        description: image digest (e.g. sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef)
        value: ${{ jobs.build.outputs.digest }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ inputs.image }}
          flavor: ${{ inputs.flavor }}
      - uses: int128/docker-build-cache-config-action@v1
        id: cache
        with:
          image: ${{ inputs.image }}/cache
          flavor: ${{ inputs.flavor }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        id: build
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          context: ${{ inputs.context }}
          platforms: ${{ inputs.platforms }}
