name: build-multi-architecture

on:
  workflow_call:
    inputs:
      context:
        description: context of docker/build-push-action
        type: string
        required: false
      build-args:
        description: build-args of docker/build-push-action
        type: string
        required: false
      platforms:
        description: List of platforms (JSON string)
        type: string
        default: |
          ["linux/amd64", "linux/arm64"]
      mount-actions-cache:
        description: If set, mount actions/cache into the builder container
        type: boolean
        required: false

jobs:
  for:
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(inputs.platforms) }}
    uses: ./.github/workflows/build.yaml
    with:
      context: ${{ inputs.context }}
      build-args: ${{ inputs.build-args }}
      platforms: ${{ matrix.platform }}
      # avoid overwriting the latest tag because metadata-action does not add a suffix to it
      flavor: latest=false,suffix=-${{ matrix.platform }}
      mount-actions-cache: ${{ inputs.mount-actions-cache }}

  multi-architecture:
    needs:
      - for
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@31cebacef4805868f9ce9a0cb03ee36c32df2ac4 # v5.3.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: suffixes
        env:
          platforms: ${{ inputs.platforms }}
        with:
          result-encoding: string
          script: |
            const platforms = JSON.parse(process.env.platforms)
            return platforms.map((platform) => `-${platform.replaceAll(/\//g, '-')}`).join(`\n`)
      - uses: int128/docker-manifest-create-action@c2b8a8199bbf49c2475f8c80a778afc65fd4198a # v1.9.0
        with:
          tags: ${{ steps.metadata.outputs.tags }}
          suffixes: ${{ steps.suffixes.outputs.result }}
