name: test

on:
  push:
    branches:
      - v1
    paths:
      - .github/workflows/test.yaml
      - .github/workflows/build.yaml
      - .github/workflows/build-multi-architecture.yaml
      - fixtures/**
    tags:
      - v*
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - .github/workflows/build.yaml
      - .github/workflows/build-multi-architecture.yaml
      - fixtures/**

concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-version:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      go-version: ${{ steps.go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: go-version
        run: echo "go-version=$(sed -ne '/^go /s/^go //p' go.mod)" >> "$GITHUB_OUTPUT"
        working-directory: fixtures

  build:
    needs: go-version
    uses: ./.github/workflows/build-multi-architecture.yaml
    with:
      context: fixtures
      build-args: |
        go_version=${{ needs.go-version.outputs.go-version }}

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: docker/metadata-action@31cebacef4805868f9ce9a0cb03ee36c32df2ac4 # v5.3.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
      - run: docker run --rm ${{ steps.metadata.outputs.tags }}
